name: Update Submissions List

on:
  push:
    branches: ['main']
    paths:
      - 'submissions.json'
  schedule:
    - cron: '0 0 * * *'

jobs:
  update:
    runs-on: windows-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - run: |
          git status
          git checkout main submissions.json
          git status
          git add submissions.json
          git status
          git commit -m "Automatically updated submissions.json"
          git status
          git push origin gh-pages
          git status
