name: Update Submissions List

on:
  push:
    branches: ['main']
    paths:
      - 'submissions.json'
  schedule:
    - cron: '0 0 * * *'

jobs:
  update:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout main submissions.json
          git add submissions.json
          git commit -m "Automatically updated submissions.json"
          git push origin gh-pages
